<!-- DataTables  & Plugins -->
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>JSZip-2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>pdfmake-0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>pdfmake-0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>DataTables-1.12.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>DataTables-1.12.1/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Buttons-2.2.3/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Buttons-2.2.3/js/buttons.bootstrap4.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Buttons-2.2.3/js/buttons.colVis.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Buttons-2.2.3/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Buttons-2.2.3/js/buttons.print.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>ColReorder-1.5.6/js/dataTables.colReorder.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>DateTime-1.1.2/js/dataTables.dateTime.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>FixedColumns-4.1.0/js/dataTables.fixedColumns.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>FixedHeader-3.2.3/js/dataTables.fixedHeader.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>KeyTable-2.7.0/js/dataTables.keyTable.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Responsive-2.3.0/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Responsive-2.3.0/js/responsive.bootstrap4.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>RowGroup-1.2.0/js/dataTables.rowGroup.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>RowReorder-1.2.8/js/dataTables.rowReorder.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Scroller-2.0.6/js/dataTables.scroller.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>SearchBuilder-1.3.3/js/dataTables.searchBuilder.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>SearchBuilder-1.3.3/js/searchBuilder.bootstrap4.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>SearchPanes-2.0.1/js/dataTables.searchPanes.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>SearchPanes-2.0.1/js/searchPanes.bootstrap4.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>Select-1.4.0/js/dataTables.select.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>StateRestore-1.1.1/js/dataTables.stateRestore.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets/DataTables/');?>StateRestore-1.1.1/js/stateRestore.bootstrap4.min.js"></script>